### ISSUE TITLE
findDecision(obj) and accuracy giving weird results

### ISSUE THREAD

**Issue by gabriellamelia** [serengil/chefboost#1]
I try to run this code:
```
import Chefboost as chef
import pandas as pd

if __name__ == "__main__":
    df = pd.read_csv("dataset/golf.txt")
    
    config = {'algorithm': 'C4.5'}
    model = chef.fit(df, config)
```
and then when i check outputs/rules/rules.py this is what i get :
```
def findDecision(obj): #obj[0]: Outlook, obj[1]: Temp., obj[2]: Humidity, obj[3]: Wind
   if obj[2] == 'Rain':
      if obj[0] == 'Weak':
         return 'Yes'
      elif obj[0] == 'Strong':
         return 'No'
   elif obj[2] == 'Sunny':
      if obj[1] == 'High':
         return 'No'
      elif obj[1] == 'Normal':
         return 'Yes'
   elif obj[2] == 'Overcast':
      return 'Yes'
```
obj[0] isn't Outlook, but Wind.. and also, sometimes i get accuracy 0% after running the code 2 or 3 times..

**Comment by serengil** [comment]
I cannot create same trouble in my environment.
Please run print(df) before fit line.

**Comment by gabriellamelia** [comment]
This is the result for print(df)

![Capture](https://user-images.githubusercontent.com/27410949/64218387-955c4780-ceeb-11e9-9977-5cd3ec1de5e2.PNG)

**Comment by serengil** [comment]
What is your python and pandas versions? My testings are performed on the following versions

C:\>python --version
Python 3.6.4 :: Anaconda, Inc.

pip install pandas==0.22.0
pip install numpy==1.14.0
pip install tqdm==4.30.0

**Comment by gabriellamelia** [comment]
Python 3.7.4

Pandas 0.25.1
Numpy 1.17.1
Tqdm 4.35.0
