### ISSUE TITLE
Parallelism does not work properly

### ISSUE THREAD

**Issue by rmallof** [serengil/chefboost#10]
Hi,

I'm testing the library using the following code snippet:

config = {
    'algorithm': 'C4.5', 
    #'enableParallelism': True, 'num_cores': 32,
}
model = chef.fit(df, config = config)

Which prints: "finished in  9.606534719467163  seconds"

Then, enabling parallelism uncommenting the line in the config, it never finishes but it uses 100% of CPU for a really long time - much more than 10 seconds

**Comment by serengil** [comment]
If you do not have really 32 cores, then starting your process 32 parallel will cause bottleneck. Recommended value is half your physical cores.

**Comment by DidiDerDenker** [comment]
Hi, I think I have found the error. When multiprocessing, the open files are not closed, which leads to permission errors. Instead of "f = open(...)" it would be better to use "with open(...)". This occurs with the load_model() function.
