### ISSUE TITLE
what is the method used to estimate the accuray rate and precision rate ?

### ISSUE THREAD

**Issue by youcef-Ismael** [serengil/chefboost#12]
did you used the cross validation k fold or what is the method that you have used to calculate these rates ?

**Comment by serengil** [comment]
accuracy metrics are calculating for train set by default. But you can still calculate those metrics for your validation / test set as well. Cross validation is not covered yet.

```
from chefboost import Chefboost as cb
model = cb.fit(df, config)
cb.evaluate(model, validation_df)
```

**Comment by macazaka** [comment]
Is there a way to pass the accuracy level, label and confusion matrix to specific variables?
