### ISSUE TITLE
I had just 3000 samples, but it is taking forever, (num_cores = 2). Any suggestions??

### ISSUE THREAD

**Issue by ManoharSai2000** [serengil/chefboost#14]

**Comment by serengil** [comment]
How many columns do you have?

**Comment by serengil** [comment]
If your columns are numerical, then the library will spend much more time.

I recommend you to use random forest. That will split data set into several data sets and it will decrease running time.

**Comment by ManoharSai2000** [comment]
Thanks for the tip! Also, does this code use Gain Ratio?

Thanks in advance.

**Comment by serengil** [comment]
Depends on the configuration

`config = {'algorithm': 'C4.5', 'enableRandomForest': True, 'num_of_trees': 15}`

**Comment by serengil** [comment]
I published a new release focusing on parallelism mechanisim. Now, parallelism is enabled by default. Please re-try your case.
