### ISSUE TITLE
What about plotting?

### ISSUE THREAD

**Issue by MatiasManevi** [serengil/chefboost#2]
That.

What about plotting dear friend?. You have made an awesome work but still missing this great functionallity.

Im new on Python. Are the chefboost outcomes prepared to be plotted and show on a picture the tree, for example? 

Thanks in advance!

**Comment by serengil** [comment]
Thank you for your feedback. I plan to add visualization support but this would not be an issue. That's why, I'm going to close this one.

**Comment by MatiasManevi** [comment]
Great! Thanks for the quik reply

**Comment by matcruz12** [comment]
i am getting intendation error
