### ISSUE TITLE
Any Tree Traversal API or Example?

### ISSUE THREAD

**Issue by dand-oss** [serengil/chefboost#20]
I am interested in plotting chef trees, particularly decision path for a sample.

A generic traversal iterator call would allow users to dump rule in different formats or create various plots with networkx/pygraphviz/matplotlib/dtreeviz/treeinterpreter ex https://stackoverflow.com/questions/20224526/how-to-extract-the-decision-rules-from-scikit-learn-decision-tree/39772170

1. Is there an example of DFS/BFS generator for traversing the nodes?  
 
ex sklearn DFS via structure & decision path
https://scikit-learn.org/stable/auto_examples/tree/plot_unveil_tree_structure.html

ex sklearn BFS generator
https://stackoverflow.com/questions/61203080/traversal-of-sklearn-decision-tree

2. does chef have anything like decision_path() in scikit?

decision_path()
https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier.decision_path

I don't mind adding this, looking for a guide to the internals of chefboost - reconstructRules might be the closes to a traversal?

Reference
https://github.com/serengil/chefboost/issues/20
https://github.com/serengil/chefboost/issues/2

**Comment by serengil** [comment]
closed due to inactivity
