### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by PeacehouseAK** [serengil/chefboost#21]
While using C4.5 i get indentation error

config = {'algorithm': 'C4.5'}
model = chef.fit(df, config = config, target_label = 'party')

_[INFO]:  1 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
  File "outputs/rules/rules.py", line 37
    else: return 'no'
       ^
IndentationError: expected an indented block_

**Comment by serengil** [comment]
May I see your dataset?

**Comment by matcruz12** [comment]
try redusing the number of features using feature selection

**Comment by serengil** [comment]
closed due to inactivity
