### ISSUE TITLE
Paralellism default value is True

### ISSUE THREAD

**Issue by anapaulamendes** [serengil/chefboost#22]
In the documentation it says that the default value to allow parallelism is False, but checking the code and commit history the default value is True.

It is necessary to adjust the documentation to be consistent with the code.

Code: https://github.com/serengil/chefboost/blob/5e1477af150d1dd16f9bc5e4a46acb3dc5f63ea8/chefboost/commons/functions.py#L85
README: https://github.com/serengil/chefboost/tree/5e1477af150d1dd16f9bc5e4a46acb3dc5f63ea8#paralellism

**Comment by serengil** [comment]
Merged the pull request. Thank you for your contribution.
