### ISSUE TITLE
feature_importance incorrect?

### ISSUE THREAD

**Issue by DKQin** [serengil/chefboost#29]
when I checked the function feature_importance(rules)  in Chefboost.py, I found the process to caculate the child_score of a node is through  "_if child_rule["depth"] == current_depth + 1:_",  I dont know if I misunderstand the meaning of child_score, but I think the child node may not refer to the nodes at the same depth.

here is some of my data: (Only in this section does WBC appear)

{"feature": "WBC", "instances": 21, "metric_value": 0.7025, "depth": 5}
if obj[24]<=13.55:
	{"feature": "HGB", "instances": 20, "metric_value": 0.6098, "depth": 6} 
	if obj[26]<=65.0:
		{"feature": "Infusion volume", "instances": 19, "metric_value": 0.4855, "depth": 7}
		if obj[58]>500.0:
			{"feature": "MV_A", "instances": 18, "metric_value": 0.3095, "depth": 8}
			................
                        ...............
		elif obj[58]<=500.0:
			return 'yes'
		else: return 'yes'
	elif obj[26]>65.0:
		return 'yes'
	else: return 'yes'
elif obj[24]>13.55: 
	return 'yes'
else: return 'yes'

I think the feature_importance of WBC (before normalize) should be caculate by this:
WBC = 21 * 0.7025 - 20 * 0.6098

but in fact Chefboost caculate by this:
{"feature": "WBC", "instances": 21, "metric_value": 0.7025, "depth": 5}
child: {'feature': 'HGB', 'instances': 667, 'metric_value': 0.0295, 'depth': 6}
child: {'feature': 'Infusion volume', 'instances': 16, 'metric_value': 0.3373, 'depth': 6}
child: {'feature': 'HGB', 'instances': 20, 'metric_value': 0.6098, 'depth': 6}
score: -22.516799999999996

WBC = 21*0.7025 - 667*0.0295 - 16*0.3373 - 20*0.6098 = -22.51679 ( even a negative value )

as you can see,  _HGB( instances 667)_ and _Infusion volume_ are be consider into child to caculate, so I wonder that
which one is right?

**Comment by serengil** [comment]
nope that is totally correct. wbc node has 3 childs and we need to subtract child nodes metric x instances to parent node.

you find out the feature importance in decision trees on [this tutorial](https://sefiks.com/2020/04/06/feature-importance-in-decision-trees/).
