### ISSUE TITLE
Unreasonable training time when I make a simple change

### ISSUE THREAD

**Issue by LuisGPMa** [serengil/chefboost#31]
So I am training a CHAID decision tree for multiclass classification, and the target variable is a string. Other than the target, I have 4 other features, two of which I want to be string type. When I train the model with only one feature as string, training takes about 15 minutes. But when I convert the other feature I wish to be treated as categorical to string, training takes forever (entire day and no result).

What could be causing this?

**Comment by serengil** [comment]
can you share the data set?

**Comment by LuisGPMa** [comment]
Unfortunately I can't, sorry.

**Comment by serengil** [comment]
so, i cannot resolve your problem
