### ISSUE TITLE
Cheefbost result is not returned

### ISSUE THREAD

**Issue by gizemkilicoglu** [serengil/chefboost#48]
I used this library like in documentation using the same dataset but the result didn't return.
Just showing below text but process didn't complete.

from chefboost import Chefboost as chef
config = {'algorithm': 'CHAID'}
model = cb.fit(df, config)

[INFO]:  40 CPU cores will be allocated in parallel running
CHAID  tree is going to be built...

Python version 3.8

**Comment by serengil** [comment]
If dataset is too big, then it may still be processing. What is the size of your dataset?

**Comment by gizemkilicoglu** [comment]
I solved it.  After changing enableParallelism param False it returned. But now I'am always getting  0 accuracy for 10.000 row 7 column data

**Comment by serengil** [comment]
Then chaid cannot work for your dataset.
