### ISSUE TITLE
Chaid model result always return 0 accuracy

### ISSUE THREAD

**Issue by gizemkilicoglu** [serengil/chefboost#49]
I'am using chefboost for CHAID algorithm. Dataset contains 10000 rows and 7 columns and fit object always return 0 accuracy. What could be causing this, can you help me?
I also want to visualize tree graph how can I do this?

config={"algorithm":"CHAID",'enableParallelism': False}
model=cb.fit(df.loc[:10000,independent_variable_columns],config,target_label='Decision')

CHAID  tree is going to be built...

finished in  6.883694887161255  seconds

Evaluate  train set

Accuracy:  0.0 % on  10001  instances
Labels:  [0 1]
Confusion matrix:  [[0, 0], [0, 0]]
Precision:  0.0 %, Recall:  0.0 %, F1:  0.0 %

**Comment by serengil** [comment]
Would you please share dataset?

**Comment by serengil** [comment]
oh if the column types are actually classes instead of real numeric values, then you should make them string.

e.g. instead of 0, make it class_0.

Otherwise, chaid will build trees with rules being greater or less than a threshold value as explained in this video: https://www.youtube.com/watch?v=YTC7sTXDmWk

**Comment by gizemkilicoglu** [comment]
The problem was solved, the model worked thank you so much :)

How can I visualize the tree ?

**Comment by serengil** [comment]
trees cannot be visualized with chefboost, you can just check the output .py files out.

**Comment by gizemkilicoglu** [comment]
This is so sad. Do you know any other lib for visualization using rules.py file?

**Comment by serengil** [comment]
nope
