### ISSUE TITLE
Only Regression Tree is Built

### ISSUE THREAD

**Issue by danialcheung** [serengil/chefboost#5]
No matter what configuration I give, it seems to always default to building a Regression Tree.
I've tried putting in a non-existent value as well, but there are no issues there as it just throws an error. 

Code:
```python
from chefboost import Chefboost as cb
import pandas as pd

df = pd.read_csv("~/Downloads/kmodes_fillna_cluster.csv")

config = {'algorithm': 'C4.5'}
model = cb.fit(df, config)
```

Output:
```
Regression  tree is going to be built...
MAE:  0.10815602836879432
RMSE:  0.2325467999874373
Mean:  0.2872340425531915
MAE / Mean:  37.654320987654316 %
RMSE / Mean:  80.96073777340409 %
finished in  1.4060499668121338  seconds
```

**Comment by serengil** [comment]
Could you share the data set "~/Downloads/kmodes_fillna_cluster.csv". If its decision column is in type of numeric, then regression tree will be built, this is normal.

**Comment by serengil** [comment]
Set the status of this issue closed.

**Comment by danialcheung** [comment]
Ah yes thank you, I had a feeling I was doing something dumb. Works as it should now!
