### ISSUE TITLE
Last available PyPi version is from Feb 15, 2022 thus is missing fixes patched from other issues.

### ISSUE THREAD

**Issue by aianta** [serengil/chefboost#50]
title, specifically ran into #34 myself before tracking down the difference between the master branch of the repo and my installed files.  

For anyone else with this issue, you can use `pip install git+https://github.com/serengil/chefboost.git` to install directly from the git repo.

**Comment by serengil** [comment]
pypi version is 0.0.17 and source code's version is 0.0.18

need to publish 18th release
