### ISSUE TITLE
spawn make it unable to run on linux

### ISSUE THREAD

**Issue by tri-bao** [serengil/chefboost#51]
I guess because of [This line](https://github.com/serengil/chefboost/blob/9d5697ae98ca64734fc62df1f1f8591c04801bea/chefboost/Chefboost.py#L151) in Chefboost.py `set_start_method("spawn", force=True)`

I'm on linux, and I'm unable to run `chef.fit` both in jupyter and in a main (`if __name__ == '__main__':`) unless I disable the parallelism (`enableParallelism`: False)

**Comment by serengil** [comment]
v0.0.18 release is published recently, now enableParallelism is False by default
