### ISSUE TITLE
Parallelism do not seems to be working

### ISSUE THREAD

**Issue by jairodelgado** [serengil/chefboost#8]
Hi,

I've used the following code:

````python

if __name__ == '__main__':
    config = {'algorithm': 'Regression', 'enableParallelism' : True, 'enableGBM': True, 'epochs': 10, 'learning_rate': 0.01}
    model = chef.fit(df_tree_train, config)

````

and when I check my CPU usage I see that only one core is being used. Why aren't all my cores being used?

**Comment by serengil** [comment]
Hello, I checked multiprocessing for GBM. CPU usage has never exceeded 100% but performance tab of task manager shows that 4 virtual cores are running when I call fit command. 

BTW, Training.py has a line mentioning the number of cores. Could you increase this value with editing on your local environment. ı will set this value with dynamically in the next feature.

`num_cores = 1`

**Comment by serengil** [comment]
I published a new release focusing on parallelism mechanisim. Now, parallelism is enabled by default. Please re-try your case.
